name: 🍎 MacOS
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  macOS:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: brew install cmake sdl2 openal-soft

      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_15.0.1.app

      - name: CMake
        run: cmake -S ./neo -B build -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=${{ matrix.lib-type }} -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DSDL2=ON -DFFMPEG=OFF -DBINKDEC=ON ../neo -Wno-dev

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }}
